version: '3.8'

services:
  frontend:
    build: ./frontend
    container_name: frontend_c
    ports:
      - "80:80"
    env_file:
      - ./frontend/.env
    networks:
      - frontend
    

  backend:
    build: ./backend
    container_name: backend_c
    ports:
      - "127.0.0.1:3000:3000"
    networks:
      - backend
      - pgpostgres
    env_file:
      - ./backend/.env
    depends_on:
      - database
    
    

      
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_c
    environment:
        PGADMIN_DEFAULT_EMAIL: admin@example.com
        PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "6000:80"
    networks:
      - pgpostgres

networks:
  frontend:
  backend:
  pgpostgres:

